name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Package-Templatess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checks if pylint score is above 7.0
        run: |
          for d in */ ; do
            cd "$d" && tar -cvf ../$(basename $d).tar * && cd ../
          done
      - uses: actions/upload-artifact@v3
        with:
          name: templates
          path: *.tar
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}